In [50]:
import requests
import pandas as pd

In [51]:
reportes = pd.read_csv('DATA-REPORTES.csv')
permisos = pd.read_csv('DATA-PERMISOS.csv')
usuarios = pd.read_csv('DATA-USUARIOS.csv')

In [36]:
columnas_eliminar = ['group', 'module', 'name', 'description', 'version', 'active']

# Eliminar las columnas
reportes = reportes.drop(columns=columnas_eliminar)

In [37]:
reportes = reportes[reportes['free']!=True]

In [38]:
columnas_eliminar = ['free','limited','restricted']
reportes = reportes.drop(columns=columnas_eliminar)

In [39]:
columnas_eliminar = ['id']
permisos = permisos.drop(columns=columnas_eliminar)

In [40]:
permisosUsuarios = pd.merge(usuarios, permisos, on='username', how='inner')

In [41]:
permisosUsuarios = pd.merge(permisosUsuarios, reportes, on='link', how='inner')

In [43]:
columnas_eliminar = ['username', 'link']
permisosUsuarios = permisosUsuarios.drop(columns=columnas_eliminar)
permisosUsuarios = permisosUsuarios.rename(columns={'id_x': 'userId'})
permisosUsuarios = permisosUsuarios.rename(columns={'id_y': 'reportId'})

In [44]:
permisosUsuarios

     userId  reportId
0         1        18
1         3        18
2         4        18
3         5        18
4         7        18
..      ...       ...
869       3         1
870      23         1
871       3         2
872      13         2
873      23         2

[874 rows x 2 columns]

In [49]:
import warnings
from urllib3.exceptions import InsecureRequestWarning

# Ignorar solo las advertencias de InsecureRequestWarning
warnings.simplefilter('ignore', InsecureRequestWarning)

import pandas as pd
import requests

# Datos de inicio de sesión
login_url = 'http://10.0.28.15:3000/auth/login'
login_data = {
    'username': 'admin',  # Cambia esto por tu nombre de usuario
    'password': '365298',  # Cambia esto por tu contraseña
    'systemcode': 'SAD'
}

# Realizar la solicitud de inicio de sesión
login_response = requests.post(login_url, json=login_data, verify=False)

if login_response.status_code == 200:
    token = login_response.json()['token']
    print('Login exitoso. Token obtenido.')
else:
    print('Error en el login:', login_response.json())
    exit()

# URL para crear usuarios
create_user_url = 'http://10.0.28.15:3000/user/add-report'

# Headers con el token de autenticación
headers = {
    'x-access-token': token,
    'Content-Type': 'application/json'
}

# Crear usuarios
for index, row in permisosUsuarios.iterrows():
    user_data = {
        'userId': int(row['userId']),  # Convertir a tipo int
        'reportId': int(row['reportId'])  # Convertir a tipo int
    }
    create_user_response = requests.post(create_user_url, headers=headers, json=user_data, verify=False)
    
    try:
        response_json = create_user_response.json()
    except ValueError:  # includes simplejson.decoder.JSONDecodeError
        response_json = create_user_response.text

    if create_user_response.status_code == 201:
        print(f"Usuario {row['userId']} y Modulo {row['reportId']} relacionado exitosamente.")
    else:
        print(f"Error al crear el permiso para {row['userId']} en Modulo {row['reportId']}: {response_json}")

print('Proceso completado.')

Login exitoso. Token obtenido.
Usuario 1 y Modulo 18 relacionado exitosamente.
Usuario 3 y Modulo 18 relacionado exitosamente.
Usuario 4 y Modulo 18 relacionado exitosamente.
Usuario 5 y Modulo 18 relacionado exitosamente.
Usuario 7 y Modulo 18 relacionado exitosamente.
Usuario 8 y Modulo 18 relacionado exitosamente.
Usuario 10 y Modulo 18 relacionado exitosamente.
Usuario 11 y Modulo 18 relacionado exitosamente.
Usuario 12 y Modulo 18 relacionado exitosamente.
Usuario 13 y Modulo 18 relacionado exitosamente.
Usuario 14 y Modulo 18 relacionado exitosamente.
Usuario 15 y Modulo 18 relacionado exitosamente.
Usuario 16 y Modulo 18 relacionado exitosamente.
Usuario 17 y Modulo 18 relacionado exitosamente.
Usuario 18 y Modulo 18 relacionado exitosamente.
Usuario 19 y Modulo 18 relacionado exitosamente.
Usuario 20 y Modulo 18 relacionado exitosamente.
Usuario 21 y Modulo 18 relacionado exitosamente.
Usuario 22 y Modulo 18 relacionado exitosamente.
Usuario 23 y Modulo 18 relacionado exitosamente.
Usuario 36 y Modulo 18 relacionado exitosamente.
Usuario 37 y Modulo 18 relacionado exitosamente.
Usuario 38 y Modulo 18 relacionado exitosamente.
Usuario 40 y Modulo 18 relacionado exitosamente.
Usuario 41 y Modulo 18 relacionado exitosamente.
Usuario 43 y Modulo 18 relacionado exitosamente.
Usuario 47 y Modulo 18 relacionado exitosamente.
Usuario 49 y Modulo 18 relacionado exitosamente.
Usuario 50 y Modulo 18 relacionado exitosamente.
Usuario 51 y Modulo 18 relacionado exitosamente.
Usuario 52 y Modulo 18 relacionado exitosamente.
Usuario 53 y Modulo 18 relacionado exitosamente.
Usuario 54 y Modulo 18 relacionado exitosamente.
Usuario 55 y Modulo 18 relacionado exitosamente.
Usuario 56 y Modulo 18 relacionado exitosamente.
Usuario 57 y Modulo 18 relacionado exitosamente.
Usuario 58 y Modulo 18 relacionado exitosamente.
Usuario 59 y Modulo 18 relacionado exitosamente.
Usuario 60 y Modulo 18 relacionado exitosamente.
Usuario 61 y Modulo 18 relacionado exitosamente.
Usuario 62 y Modulo 18 relacionado exitosamente.
Usuario 72 y Modulo 18 relacionado exitosamente.
Usuario 73 y Modulo 18 relacionado exitosamente.
Usuario 75 y Modulo 18 relacionado exitosamente.
Usuario 77 y Modulo 18 relacionado exitosamente.
Usuario 78 y Modulo 18 relacionado exitosamente.
Usuario 80 y Modulo 18 relacionado exitosamente.
Usuario 84 y Modulo 18 relacionado exitosamente.
Usuario 85 y Modulo 18 relacionado exitosamente.
Usuario 1 y Modulo 7 relacionado exitosamente.
Usuario 3 y Modulo 7 relacionado exitosamente.
Usuario 4 y Modulo 7 relacionado exitosamente.
Usuario 5 y Modulo 7 relacionado exitosamente.
Usuario 6 y Modulo 7 relacionado exitosamente.
Usuario 7 y Modulo 7 relacionado exitosamente.
Usuario 8 y Modulo 7 relacionado exitosamente.
Usuario 10 y Modulo 7 relacionado exitosamente.
Usuario 11 y Modulo 7 relacionado exitosamente.
Usuario 12 y Modulo 7 relacionado exitosamente.
Usuario 13 y Modulo 7 relacionado exitosamente.
Usuario 14 y Modulo 7 relacionado exitosamente.
Usuario 15 y Modulo 7 relacionado exitosamente.
Usuario 16 y Modulo 7 relacionado exitosamente.
Usuario 17 y Modulo 7 relacionado exitosamente.
Usuario 18 y Modulo 7 relacionado exitosamente.
Usuario 19 y Modulo 7 relacionado exitosamente.
Usuario 20 y Modulo 7 relacionado exitosamente.
Usuario 21 y Modulo 7 relacionado exitosamente.
Usuario 22 y Modulo 7 relacionado exitosamente.
Usuario 23 y Modulo 7 relacionado exitosamente.
Usuario 36 y Modulo 7 relacionado exitosamente.
Usuario 37 y Modulo 7 relacionado exitosamente.
Usuario 38 y Modulo 7 relacionado exitosamente.
Usuario 41 y Modulo 7 relacionado exitosamente.
Usuario 44 y Modulo 7 relacionado exitosamente.
Usuario 49 y Modulo 7 relacionado exitosamente.
Usuario 50 y Modulo 7 relacionado exitosamente.
Usuario 51 y Modulo 7 relacionado exitosamente.
Usuario 52 y Modulo 7 relacionado exitosamente.
Usuario 53 y Modulo 7 relacionado exitosamente.
Usuario 54 y Modulo 7 relacionado exitosamente.
Usuario 55 y Modulo 7 relacionado exitosamente.
Usuario 56 y Modulo 7 relacionado exitosamente.
Usuario 57 y Modulo 7 relacionado exitosamente.
Usuario 58 y Modulo 7 relacionado exitosamente.
Usuario 59 y Modulo 7 relacionado exitosamente.
Usuario 60 y Modulo 7 relacionado exitosamente.
Usuario 61 y Modulo 7 relacionado exitosamente.
Usuario 62 y Modulo 7 relacionado exitosamente.
Usuario 63 y Modulo 7 relacionado exitosamente.
Usuario 64 y Modulo 7 relacionado exitosamente.
Usuario 65 y Modulo 7 relacionado exitosamente.
Usuario 66 y Modulo 7 relacionado exitosamente.
Usuario 67 y Modulo 7 relacionado exitosamente.
Usuario 68 y Modulo 7 relacionado exitosamente.
Usuario 69 y Modulo 7 relacionado exitosamente.
Usuario 70 y Modulo 7 relacionado exitosamente.
Usuario 71 y Modulo 7 relacionado exitosamente.
Usuario 73 y Modulo 7 relacionado exitosamente.
Usuario 75 y Modulo 7 relacionado exitosamente.
Usuario 78 y Modulo 7 relacionado exitosamente.
Usuario 81 y Modulo 7 relacionado exitosamente.
Usuario 84 y Modulo 7 relacionado exitosamente.
Usuario 85 y Modulo 7 relacionado exitosamente.
Usuario 1 y Modulo 17 relacionado exitosamente.
Usuario 3 y Modulo 17 relacionado exitosamente.
Usuario 4 y Modulo 17 relacionado exitosamente.
Usuario 21 y Modulo 17 relacionado exitosamente.
Usuario 23 y Modulo 17 relacionado exitosamente.
Usuario 37 y Modulo 17 relacionado exitosamente.
Usuario 41 y Modulo 17 relacionado exitosamente.
Usuario 43 y Modulo 17 relacionado exitosamente.
Usuario 50 y Modulo 17 relacionado exitosamente.
Usuario 51 y Modulo 17 relacionado exitosamente.
Usuario 52 y Modulo 17 relacionado exitosamente.
Usuario 53 y Modulo 17 relacionado exitosamente.
Usuario 54 y Modulo 17 relacionado exitosamente.
Usuario 55 y Modulo 17 relacionado exitosamente.
Usuario 56 y Modulo 17 relacionado exitosamente.
Usuario 57 y Modulo 17 relacionado exitosamente.
Usuario 58 y Modulo 17 relacionado exitosamente.
Usuario 59 y Modulo 17 relacionado exitosamente.
Usuario 61 y Modulo 17 relacionado exitosamente.
Usuario 62 y Modulo 17 relacionado exitosamente.
Usuario 63 y Modulo 17 relacionado exitosamente.
Usuario 64 y Modulo 17 relacionado exitosamente.
Usuario 65 y Modulo 17 relacionado exitosamente.
Usuario 66 y Modulo 17 relacionado exitosamente.
Usuario 67 y Modulo 17 relacionado exitosamente.
Usuario 68 y Modulo 17 relacionado exitosamente.
Usuario 69 y Modulo 17 relacionado exitosamente.
Usuario 70 y Modulo 17 relacionado exitosamente.
Usuario 71 y Modulo 17 relacionado exitosamente.
Usuario 72 y Modulo 17 relacionado exitosamente.
Usuario 73 y Modulo 17 relacionado exitosamente.
Usuario 75 y Modulo 17 relacionado exitosamente.
Usuario 81 y Modulo 17 relacionado exitosamente.
Usuario 82 y Modulo 17 relacionado exitosamente.
Usuario 84 y Modulo 17 relacionado exitosamente.
Usuario 85 y Modulo 17 relacionado exitosamente.
Usuario 1 y Modulo 42 relacionado exitosamente.
Usuario 3 y Modulo 42 relacionado exitosamente.
Usuario 4 y Modulo 42 relacionado exitosamente.
Usuario 5 y Modulo 42 relacionado exitosamente.
Usuario 6 y Modulo 42 relacionado exitosamente.
Usuario 7 y Modulo 42 relacionado exitosamente.
Usuario 8 y Modulo 42 relacionado exitosamente.
Usuario 10 y Modulo 42 relacionado exitosamente.
Usuario 11 y Modulo 42 relacionado exitosamente.
Usuario 12 y Modulo 42 relacionado exitosamente.
Usuario 13 y Modulo 42 relacionado exitosamente.
Usuario 14 y Modulo 42 relacionado exitosamente.
Usuario 15 y Modulo 42 relacionado exitosamente.
Usuario 16 y Modulo 42 relacionado exitosamente.
Usuario 17 y Modulo 42 relacionado exitosamente.
Usuario 18 y Modulo 42 relacionado exitosamente.
Usuario 19 y Modulo 42 relacionado exitosamente.
Usuario 20 y Modulo 42 relacionado exitosamente.
Usuario 21 y Modulo 42 relacionado exitosamente.
Usuario 22 y Modulo 42 relacionado exitosamente.
Usuario 23 y Modulo 42 relacionado exitosamente.
Usuario 36 y Modulo 42 relacionado exitosamente.
Usuario 37 y Modulo 42 relacionado exitosamente.
Usuario 38 y Modulo 42 relacionado exitosamente.
Usuario 41 y Modulo 42 relacionado exitosamente.
Usuario 43 y Modulo 42 relacionado exitosamente.
Usuario 44 y Modulo 42 relacionado exitosamente.
Usuario 47 y Modulo 42 relacionado exitosamente.
Usuario 49 y Modulo 42 relacionado exitosamente.
Usuario 50 y Modulo 42 relacionado exitosamente.
Usuario 51 y Modulo 42 relacionado exitosamente.
Usuario 52 y Modulo 42 relacionado exitosamente.
Usuario 53 y Modulo 42 relacionado exitosamente.
Usuario 54 y Modulo 42 relacionado exitosamente.
Usuario 55 y Modulo 42 relacionado exitosamente.
Usuario 56 y Modulo 42 relacionado exitosamente.
Usuario 57 y Modulo 42 relacionado exitosamente.
Usuario 58 y Modulo 42 relacionado exitosamente.
Usuario 59 y Modulo 42 relacionado exitosamente.
Usuario 60 y Modulo 42 relacionado exitosamente.
Usuario 61 y Modulo 42 relacionado exitosamente.
Usuario 62 y Modulo 42 relacionado exitosamente.
Usuario 63 y Modulo 42 relacionado exitosamente.
Usuario 64 y Modulo 42 relacionado exitosamente.
Usuario 65 y Modulo 42 relacionado exitosamente.
Usuario 66 y Modulo 42 relacionado exitosamente.
Usuario 67 y Modulo 42 relacionado exitosamente.
Usuario 68 y Modulo 42 relacionado exitosamente.
Usuario 69 y Modulo 42 relacionado exitosamente.
Usuario 70 y Modulo 42 relacionado exitosamente.
Usuario 71 y Modulo 42 relacionado exitosamente.
Usuario 73 y Modulo 42 relacionado exitosamente.
Usuario 74 y Modulo 42 relacionado exitosamente.
Usuario 75 y Modulo 42 relacionado exitosamente.
Usuario 77 y Modulo 42 relacionado exitosamente.
Usuario 78 y Modulo 42 relacionado exitosamente.
Usuario 82 y Modulo 42 relacionado exitosamente.
Usuario 84 y Modulo 42 relacionado exitosamente.
Usuario 85 y Modulo 42 relacionado exitosamente.
Usuario 1 y Modulo 38 relacionado exitosamente.
Usuario 3 y Modulo 38 relacionado exitosamente.
Usuario 4 y Modulo 38 relacionado exitosamente.
Usuario 5 y Modulo 38 relacionado exitosamente.
Usuario 6 y Modulo 38 relacionado exitosamente.
Usuario 7 y Modulo 38 relacionado exitosamente.
Usuario 8 y Modulo 38 relacionado exitosamente.
Usuario 9 y Modulo 38 relacionado exitosamente.
Usuario 10 y Modulo 38 relacionado exitosamente.
Usuario 11 y Modulo 38 relacionado exitosamente.
Usuario 12 y Modulo 38 relacionado exitosamente.
Usuario 13 y Modulo 38 relacionado exitosamente.
Usuario 14 y Modulo 38 relacionado exitosamente.
Usuario 15 y Modulo 38 relacionado exitosamente.
Usuario 16 y Modulo 38 relacionado exitosamente.
Usuario 17 y Modulo 38 relacionado exitosamente.
Usuario 18 y Modulo 38 relacionado exitosamente.
Usuario 19 y Modulo 38 relacionado exitosamente.
Usuario 20 y Modulo 38 relacionado exitosamente.
Usuario 21 y Modulo 38 relacionado exitosamente.
Usuario 22 y Modulo 38 relacionado exitosamente.
Usuario 23 y Modulo 38 relacionado exitosamente.
Usuario 24 y Modulo 38 relacionado exitosamente.
Usuario 36 y Modulo 38 relacionado exitosamente.
Usuario 37 y Modulo 38 relacionado exitosamente.
Usuario 38 y Modulo 38 relacionado exitosamente.
Usuario 40 y Modulo 38 relacionado exitosamente.
Usuario 41 y Modulo 38 relacionado exitosamente.
Usuario 42 y Modulo 38 relacionado exitosamente.
Usuario 43 y Modulo 38 relacionado exitosamente.
Usuario 45 y Modulo 38 relacionado exitosamente.
Usuario 46 y Modulo 38 relacionado exitosamente.
Usuario 47 y Modulo 38 relacionado exitosamente.
Usuario 49 y Modulo 38 relacionado exitosamente.
Usuario 50 y Modulo 38 relacionado exitosamente.
Usuario 51 y Modulo 38 relacionado exitosamente.
Usuario 52 y Modulo 38 relacionado exitosamente.
Usuario 53 y Modulo 38 relacionado exitosamente.
Usuario 54 y Modulo 38 relacionado exitosamente.
Usuario 55 y Modulo 38 relacionado exitosamente.
Usuario 56 y Modulo 38 relacionado exitosamente.
Usuario 57 y Modulo 38 relacionado exitosamente.
Usuario 58 y Modulo 38 relacionado exitosamente.
Usuario 59 y Modulo 38 relacionado exitosamente.
Usuario 60 y Modulo 38 relacionado exitosamente.
Usuario 61 y Modulo 38 relacionado exitosamente.
Usuario 62 y Modulo 38 relacionado exitosamente.
Usuario 73 y Modulo 38 relacionado exitosamente.
Usuario 74 y Modulo 38 relacionado exitosamente.
Usuario 75 y Modulo 38 relacionado exitosamente.
Usuario 76 y Modulo 38 relacionado exitosamente.
Usuario 77 y Modulo 38 relacionado exitosamente.
Usuario 78 y Modulo 38 relacionado exitosamente.
Usuario 79 y Modulo 38 relacionado exitosamente.
Usuario 81 y Modulo 38 relacionado exitosamente.
Usuario 82 y Modulo 38 relacionado exitosamente.
Usuario 84 y Modulo 38 relacionado exitosamente.
Usuario 85 y Modulo 38 relacionado exitosamente.
Usuario 1 y Modulo 52 relacionado exitosamente.
Usuario 3 y Modulo 52 relacionado exitosamente.
Usuario 4 y Modulo 52 relacionado exitosamente.
Usuario 21 y Modulo 52 relacionado exitosamente.
Usuario 23 y Modulo 52 relacionado exitosamente.
Usuario 37 y Modulo 52 relacionado exitosamente.
Usuario 41 y Modulo 52 relacionado exitosamente.
Usuario 61 y Modulo 52 relacionado exitosamente.
Usuario 62 y Modulo 52 relacionado exitosamente.
Usuario 73 y Modulo 52 relacionado exitosamente.
Usuario 75 y Modulo 52 relacionado exitosamente.
Usuario 1 y Modulo 41 relacionado exitosamente.
Usuario 3 y Modulo 41 relacionado exitosamente.
Usuario 23 y Modulo 41 relacionado exitosamente.
Usuario 24 y Modulo 41 relacionado exitosamente.
Usuario 27 y Modulo 41 relacionado exitosamente.
Usuario 28 y Modulo 41 relacionado exitosamente.
Usuario 29 y Modulo 41 relacionado exitosamente.
Usuario 38 y Modulo 41 relacionado exitosamente.
Usuario 41 y Modulo 41 relacionado exitosamente.
Usuario 1 y Modulo 25 relacionado exitosamente.
Usuario 3 y Modulo 25 relacionado exitosamente.
Usuario 4 y Modulo 25 relacionado exitosamente.
Usuario 5 y Modulo 25 relacionado exitosamente.
Usuario 6 y Modulo 25 relacionado exitosamente.
Usuario 7 y Modulo 25 relacionado exitosamente.
Usuario 8 y Modulo 25 relacionado exitosamente.
Usuario 10 y Modulo 25 relacionado exitosamente.
Usuario 11 y Modulo 25 relacionado exitosamente.
Usuario 12 y Modulo 25 relacionado exitosamente.
Usuario 13 y Modulo 25 relacionado exitosamente.
Usuario 21 y Modulo 25 relacionado exitosamente.
Usuario 22 y Modulo 25 relacionado exitosamente.
Usuario 23 y Modulo 25 relacionado exitosamente.
Usuario 24 y Modulo 25 relacionado exitosamente.
Usuario 27 y Modulo 25 relacionado exitosamente.
Usuario 28 y Modulo 25 relacionado exitosamente.
Usuario 29 y Modulo 25 relacionado exitosamente.
Usuario 36 y Modulo 25 relacionado exitosamente.
Usuario 37 y Modulo 25 relacionado exitosamente.
Usuario 38 y Modulo 25 relacionado exitosamente.
Usuario 41 y Modulo 25 relacionado exitosamente.
Usuario 44 y Modulo 25 relacionado exitosamente.
Usuario 49 y Modulo 25 relacionado exitosamente.
Usuario 50 y Modulo 25 relacionado exitosamente.
Usuario 51 y Modulo 25 relacionado exitosamente.
Usuario 52 y Modulo 25 relacionado exitosamente.
Usuario 53 y Modulo 25 relacionado exitosamente.
Usuario 54 y Modulo 25 relacionado exitosamente.
Usuario 55 y Modulo 25 relacionado exitosamente.
Usuario 56 y Modulo 25 relacionado exitosamente.
Usuario 57 y Modulo 25 relacionado exitosamente.
Usuario 58 y Modulo 25 relacionado exitosamente.
Usuario 59 y Modulo 25 relacionado exitosamente.
Usuario 60 y Modulo 25 relacionado exitosamente.
Usuario 61 y Modulo 25 relacionado exitosamente.
Usuario 62 y Modulo 25 relacionado exitosamente.
Usuario 63 y Modulo 25 relacionado exitosamente.
Usuario 64 y Modulo 25 relacionado exitosamente.
Usuario 65 y Modulo 25 relacionado exitosamente.
Usuario 66 y Modulo 25 relacionado exitosamente.
Usuario 67 y Modulo 25 relacionado exitosamente.
Usuario 68 y Modulo 25 relacionado exitosamente.
Usuario 69 y Modulo 25 relacionado exitosamente.
Usuario 70 y Modulo 25 relacionado exitosamente.
Usuario 71 y Modulo 25 relacionado exitosamente.
Usuario 73 y Modulo 25 relacionado exitosamente.
Usuario 74 y Modulo 25 relacionado exitosamente.
Usuario 77 y Modulo 25 relacionado exitosamente.
Usuario 78 y Modulo 25 relacionado exitosamente.
Usuario 81 y Modulo 25 relacionado exitosamente.
Usuario 82 y Modulo 25 relacionado exitosamente.
Usuario 84 y Modulo 25 relacionado exitosamente.
Usuario 85 y Modulo 25 relacionado exitosamente.
Usuario 1 y Modulo 27 relacionado exitosamente.
Usuario 3 y Modulo 27 relacionado exitosamente.
Usuario 4 y Modulo 27 relacionado exitosamente.
Usuario 21 y Modulo 27 relacionado exitosamente.
Usuario 22 y Modulo 27 relacionado exitosamente.
Usuario 23 y Modulo 27 relacionado exitosamente.
Usuario 24 y Modulo 27 relacionado exitosamente.
Usuario 27 y Modulo 27 relacionado exitosamente.
Usuario 28 y Modulo 27 relacionado exitosamente.
Usuario 29 y Modulo 27 relacionado exitosamente.
Usuario 37 y Modulo 27 relacionado exitosamente.
Usuario 41 y Modulo 27 relacionado exitosamente.
Usuario 49 y Modulo 27 relacionado exitosamente.
Usuario 61 y Modulo 27 relacionado exitosamente.
Usuario 62 y Modulo 27 relacionado exitosamente.
Usuario 63 y Modulo 27 relacionado exitosamente.
Usuario 64 y Modulo 27 relacionado exitosamente.
Usuario 65 y Modulo 27 relacionado exitosamente.
Usuario 66 y Modulo 27 relacionado exitosamente.
Usuario 67 y Modulo 27 relacionado exitosamente.
Usuario 68 y Modulo 27 relacionado exitosamente.
Usuario 69 y Modulo 27 relacionado exitosamente.
Usuario 70 y Modulo 27 relacionado exitosamente.
Usuario 71 y Modulo 27 relacionado exitosamente.
Usuario 73 y Modulo 27 relacionado exitosamente.
Usuario 75 y Modulo 27 relacionado exitosamente.
Usuario 77 y Modulo 27 relacionado exitosamente.
Usuario 84 y Modulo 27 relacionado exitosamente.
Usuario 85 y Modulo 27 relacionado exitosamente.
Usuario 1 y Modulo 12 relacionado exitosamente.
Usuario 3 y Modulo 12 relacionado exitosamente.
Usuario 4 y Modulo 12 relacionado exitosamente.
Usuario 5 y Modulo 12 relacionado exitosamente.
Usuario 6 y Modulo 12 relacionado exitosamente.
Usuario 7 y Modulo 12 relacionado exitosamente.
Usuario 8 y Modulo 12 relacionado exitosamente.
Usuario 10 y Modulo 12 relacionado exitosamente.
Usuario 11 y Modulo 12 relacionado exitosamente.
Usuario 12 y Modulo 12 relacionado exitosamente.
Usuario 13 y Modulo 12 relacionado exitosamente.
Usuario 21 y Modulo 12 relacionado exitosamente.
Usuario 22 y Modulo 12 relacionado exitosamente.
Usuario 23 y Modulo 12 relacionado exitosamente.
Usuario 25 y Modulo 12 relacionado exitosamente.
Usuario 26 y Modulo 12 relacionado exitosamente.
Usuario 30 y Modulo 12 relacionado exitosamente.
Usuario 31 y Modulo 12 relacionado exitosamente.
Usuario 32 y Modulo 12 relacionado exitosamente.
Usuario 33 y Modulo 12 relacionado exitosamente.
Usuario 34 y Modulo 12 relacionado exitosamente.
Usuario 35 y Modulo 12 relacionado exitosamente.
Usuario 36 y Modulo 12 relacionado exitosamente.
Usuario 37 y Modulo 12 relacionado exitosamente.
Usuario 38 y Modulo 12 relacionado exitosamente.
Usuario 41 y Modulo 12 relacionado exitosamente.
Usuario 47 y Modulo 12 relacionado exitosamente.
Usuario 49 y Modulo 12 relacionado exitosamente.
Usuario 61 y Modulo 12 relacionado exitosamente.
Usuario 62 y Modulo 12 relacionado exitosamente.
Usuario 73 y Modulo 12 relacionado exitosamente.
Usuario 75 y Modulo 12 relacionado exitosamente.
Usuario 78 y Modulo 12 relacionado exitosamente.
Usuario 1 y Modulo 44 relacionado exitosamente.
Usuario 3 y Modulo 44 relacionado exitosamente.
Usuario 4 y Modulo 44 relacionado exitosamente.
Usuario 13 y Modulo 44 relacionado exitosamente.
Usuario 21 y Modulo 44 relacionado exitosamente.
Usuario 23 y Modulo 44 relacionado exitosamente.
Usuario 24 y Modulo 44 relacionado exitosamente.
Usuario 37 y Modulo 44 relacionado exitosamente.
Usuario 40 y Modulo 44 relacionado exitosamente.
Usuario 41 y Modulo 44 relacionado exitosamente.
Usuario 45 y Modulo 44 relacionado exitosamente.
Usuario 46 y Modulo 44 relacionado exitosamente.
Usuario 49 y Modulo 44 relacionado exitosamente.
Usuario 61 y Modulo 44 relacionado exitosamente.
Usuario 62 y Modulo 44 relacionado exitosamente.
Usuario 73 y Modulo 44 relacionado exitosamente.

In [53]:
usuarios['username'] = usuarios['username'] + '@essalud.gob.pe'

In [54]:
usuarios

    id                            username
0    1                admin@essalud.gob.pe
1    2         gctic.gsit06@essalud.gob.pe
2    3   geovanni.chiarella@essalud.gob.pe
3    4         frank.guzman@essalud.gob.pe
4    5       maria.aguilard@essalud.gob.pe
..  ..                                 ...
81  82  alberto.barrenechea@essalud.gob.pe
82  83         gctic.gsit16@essalud.gob.pe
83  84     alexander.larosa@essalud.gob.pe
84  85      german.carbonel@essalud.gob.pe
85  86         gctic.gsit05@essalud.gob.pe

[86 rows x 2 columns]

In [55]:
usuarios['username']

0                   admin@essalud.gob.pe
1            gctic.gsit06@essalud.gob.pe
2      geovanni.chiarella@essalud.gob.pe
3            frank.guzman@essalud.gob.pe
4          maria.aguilard@essalud.gob.pe
                     ...
81    alberto.barrenechea@essalud.gob.pe
82           gctic.gsit16@essalud.gob.pe
83       alexander.larosa@essalud.gob.pe
84        german.carbonel@essalud.gob.pe
85           gctic.gsit05@essalud.gob.pe
Name: username, Length: 86, dtype: object