In [31]:
from decouple import config
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime, timedelta
import time 
import datetime
from sqlalchemy import text
import oracledb
import sys


#CONEXIONES
DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="essi_etl"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena1  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine1 = create_engine(cadena1)
connection1 = engine1.connect()

DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dw_essalud"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena2  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine2 = create_engine(cadena2)
connection2 = engine2.connect()

DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dl_essi"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena3  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine3 = create_engine(cadena3)
connection3 = engine3.connect()


DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="etl_logs"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena4  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine4 = create_engine(cadena4)
connection4 = engine4.connect()




fecha_ini = pd.read_sql_query("SELECT fec_ini FROM etl_act where id_mod=16", con=connection2)
fecha_ini= fecha_ini.iloc[0, 0]

fecha_fin = pd.read_sql_query("SELECT fec_ter FROM etl_act where id_mod=16", con=connection2)
fecha_fin= fecha_fin.iloc[0, 0]


# Definir el número total de meses desde la fecha de inicio hasta la fecha actual
total_meses = (fecha_fin.year - fecha_ini.year) * 12 + (fecha_fin.month - fecha_ini.month)


for i in range(total_meses+1):
    inicioTiempo = time.time()
    now_inicio = datetime.datetime.now()

	# Calcular la fecha de inicio y fin del intervalo mensual
    fecha_ini_mes = fecha_ini
		
	# Obtener el último día del mes actual
    if fecha_fin.month==fecha_ini.month and fecha_fin.year==fecha_ini.year:
        fecha_fin_mes = fecha_fin
    else :
        ultimo_dia_mes_actual = datetime.date(fecha_ini_mes.year, fecha_ini_mes.month, 1) + datetime.timedelta(days=32)
        fecha_fin_mes = ultimo_dia_mes_actual.replace(day=1)

    fecha_ini_str = fecha_ini_mes.strftime('%Y-%m-%d')
    fecha_fin_str = fecha_fin_mes.strftime('%Y-%m-%d')

    print("Primer día del mes actual:", fecha_ini_str)
    print("Primer día del mes siguiente:", fecha_fin_str)

    fecha_ini = fecha_fin_mes

Primer día del mes actual: 2024-02-20
Primer día del mes siguiente: 2024-03-01
Primer día del mes actual: 2024-03-01
Primer día del mes siguiente: 2024-04-01
Primer día del mes actual: 2024-04-01
Primer día del mes siguiente: 2024-05-01
Primer día del mes actual: 2024-05-01
Primer día del mes siguiente: 2024-06-01
Primer día del mes actual: 2024-06-01
Primer día del mes siguiente: 2024-07-01
Primer día del mes actual: 2024-07-01
Primer día del mes siguiente: 2024-08-01
Primer día del mes actual: 2024-08-01
Primer día del mes siguiente: 2024-09-01
Primer día del mes actual: 2024-09-01
Primer día del mes siguiente: 2024-10-01
Primer día del mes actual: 2024-10-01
Primer día del mes siguiente: 2024-11-01
Primer día del mes actual: 2024-11-01
Primer día del mes siguiente: 2024-12-01
Primer día del mes actual: 2024-12-01
Primer día del mes siguiente: 2024-12-31

In [8]:
from decouple import config
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text
import oracledb
import sys


oracledb.init_oracle_client()
oracledb.version = "11.2.0.4"
sys.modules["cx_Oracle"] = oracledb
un = 'DW_ESSALUD'
pw = 'Dw_Essalud24'
hostname='10.0.1.228'
service_name="devugad"
port = 1521

engine1 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

connection1 = engine1.connect()

fecha_ini = pd.read_sql_query("SELECT fec_ini FROM etl_act where id_mod=2", con=connection1)
fecha_ini= fecha_ini.iloc[0, 0]

fecha_fin = pd.read_sql_query("SELECT fec_ter FROM etl_act where id_mod=2", con=connection1)
fecha_fin= fecha_fin.iloc[0, 0]

In [14]:

oracledb.init_oracle_client()
oracledb.version = "11.2.0.4"
sys.modules["cx_Oracle"] = oracledb
un = 'DW_ESSALUD'
pw = 'Dw_Essalud24'
hostname='10.0.1.228'
service_name="devugad"
port = 1521

engine1 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

connection1 = engine1.connect()

In [30]:
now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
query = f"UPDATE etl_act SET fec_act = TO_DATE('{now}', 'YYYY-MM-DD HH24:MI:SS') WHERE id_mod = 3"


c1= text(query)
connection1.execute(c1)

In [28]:
now2 = datetime.now().strftime('%Y-%m-%d')
query2=f"UPDATE etl_act SET fec_ini = TO_DATE('{now2}', 'YYYY-MM-DD') WHERE id_mod = 3"
c2= text(query2)
connection1.execute(c2)

In [32]:
tipdoc = pd.read_sql_query(f"SELECT id_tipdoc,cod_tdo FROM dim_tipdoc", con=connection2)
tipdoc=tipdoc.rename(columns={"id_tipdoc":"id_tdi_pac"})

In [36]:
tipdoc

   id_tdi_pac cod_tdo
0           1       1
1           2       2
2           3       3
3           4       8
4           5       6
5           6       7
6           7       9
7           8       4
8           9       5
9          10       X

In [37]:
tipdoc = pd.read_sql_query(f"SELECT id_tipdoc,cod_tdo FROM dim_tipdoc", con=connection2)
tipdoc=tipdoc.rename(columns={"id_tipdoc":"id_tdi_pac"})

In [38]:
tipdoc

   id_tdi_pac cod_tdo
0           1       1
1           2       2
2           3       3
3           4       8
4           5       6
5           6       7
6           7       9
7           8       4
8           9       5
9          10       X

In [2]:
from decouple import config
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text
import oracledb
import sys
import numpy as np

DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dw_essalud"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena2  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine2 = create_engine(cadena2)
connection2 = engine2.connect()

oracledb.init_oracle_client()
oracledb.version = "11.2.0.4"
sys.modules["cx_Oracle"] = oracledb
un = 'DW_ESSALUD'
pw = 'Dw_Essalud24'
hostname='10.0.1.228'
service_name="devugad"
port = 1521

engine1 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

connection1 = engine1.connect()

fecha_ini = pd.read_sql_query("SELECT fec_ini FROM etl_act where id_mod=3", con=connection1)
fecha_ini= fecha_ini.iloc[0, 0]

fecha_fin = pd.read_sql_query("SELECT fec_ter FROM etl_act where id_mod=3", con=connection1)
fecha_fin= fecha_fin.iloc[0, 0]


# Definir el número total de meses desde la fecha de inicio hasta la fecha actual
total_meses = (fecha_fin.year - fecha_ini.year) * 12 + (fecha_fin.month - fecha_ini.month)

In [134]:
now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
query = f"UPDATE etl_act SET fec_act = TO_DATE('{now}', 'YYYY-MM-DD HH24:MI:SS') WHERE id_mod = 3"


c1= text(query)
connection1.execute(c1)

tabla='ctcam10'
col_tabla='citambproconfec'



oracledb.init_oracle_client()
oracledb.version = "8.3.0"
sys.modules["cx_Oracle"] = oracledb
un = config("USER4_BDI_POSTGRES")
pw = config("PASS4_BDI_POSTGRES")
hostname=config("HOST4_BDI_POSTGRES")
service_name="WNET"
port = 1527

engine0 = create_engine(f'oracle://{un}:{pw}@',connect_args={
	"host": hostname,
	"port": port,
	"service_name": service_name
}
)

connection0 = engine0.connect()

query = f"""SELECT c.*, c2.PERTIPDOCIDENCOD, c2.PERDOCIDENNUM FROM {tabla} c LEFT JOIN (
SELECT PERSECNUM, PERTIPDOCIDENCOD, PERDOCIDENNUM 
FROM CMPER10
GROUP BY PERSECNUM, PERTIPDOCIDENCOD, PERDOCIDENNUM 
) c2 ON c.CITAMBPACSECNUM = c2.PERSECNUM WHERE c.{col_tabla} >= TO_DATE('{fecha_ini_str}', 'YYYY-MM-DD') AND c.{col_tabla} < TO_DATE('{fecha_fin_str}', 'YYYY-MM-DD')"""
base2 = pd.read_sql_query(query, con=connection0)

connection0.close()

tabla='ctcam10'
col_essi='fec_cit'
col_tabla='citambproconfec'
essi='essi_dat_cex001_etl'


base2 = base2.rename(columns={
'citambactcod': 'cod_act',
'citambactespcod': 'cod_sub',
'citambanufec': 'fec_anu',
'citambarehoscod': 'cod_are',
'citambcenasicod': 'cod_cas',
'citambcnvespcod': 'cnv_esp',
'citambcrefec': 'fec_cre',
'citambestctrlseg': 'ctr_seg',
'citambhorcit': 'hor_cit',
'citambipanucod': 'ip_anu',
'citambipcrecod': 'ip_cre',
'citambipmodcod': 'ip_mod',
'citambmodanucod': 'mod_anu',
'citambmodfec': 'fec_mod',
'citambnum': 'cit_num',
'citambnumord': 'ord_cit',
'citamboricenasicod': 'ori_cas',
'citambpacsecnum': 'pac_sec',
'citambperasisdocidennum': 'num_doc_med',
'citambproconcenasicod': 'cas_pro',
'citambproconfec': 'fec_cit',
'citambproconoricenasicod': 'ori_pro',
'citambproconturhorfin': 'hor_fin',
'citambproconturhorini': 'hor_ini',
'citambrep': 'cit_rep',
'citambservhoscod': 'cod_ser',
'citambsolfec': 'fec_sol',
'citambtipdocidenpercod': 'cod_tdi_med',
'citambusuanucod': 'usu_anu',
'citambusucrecod': 'usu_cre',
'citambusumodcod': 'usu_mod',
'condcitacod': 'cod_cci',
'estcitcod': 'cod_eci',
'estcitotocod': 'cod_enco',
'modotorcitacod': 'cod_oto',
'motelicitcod': 'cod_mec',
'motinacitdes': 'mot_cit',
'tipocitacod': 'cod_tci',
'pertipdocidencod': 'cod_tdi_pac',
'perdocidennum': 'num_doc_pac'
})


base1=base2

tabla='ctcam10'
col_essi='fec_cit'
essi='essi_dat_cex001_etl'
col_dat='fec_cit'
dat='dat_cext001_essi'


base2=pd.read_sql_query(f"SELECT * FROM {dat} WHERE ROWNUM <= 10", con=connection1)

In [132]:
base1['hor_ini'] = base1['hor_ini'].astype(str)
base1['hor_ini'] = np.where(base1['hor_ini'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['hor_ini'].str[-8:], base1['hor_ini'])
base1['hor_ini'] = pd.to_datetime(base1['hor_ini'], errors='coerce')
base1['hor_fin'] = base1['hor_fin'].astype(str)
base1['hor_fin'] = np.where(base1['hor_fin'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['hor_fin'].str[-8:], base1['hor_fin'])
base1['hor_fin'] = pd.to_datetime(base1['hor_fin'], errors='coerce')
base1['hor_cit'] = base1['hor_cit'].astype(str)
base1['hor_cit'] = np.where(base1['hor_cit'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['hor_cit'].str[-8:], base1['hor_cit'])
base1['hor_cit'] = pd.to_datetime(base1['hor_cit'], errors='coerce')
base1['fec_cit'] = base1['fec_cit'].astype(str)
base1['fec_cit'] = np.where(base1['fec_cit'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_cit'].str[-8:], base1['fec_cit'])
base1['fec_cit'] = pd.to_datetime(base1['fec_cit'], errors='coerce')
base1['fec_cre'] = base1['fec_cre'].astype(str)
base1['fec_cre'] = np.where(base1['fec_cre'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_cre'].str[-8:], base1['fec_cre'])
base1['fec_cre'] = pd.to_datetime(base1['fec_cre'], errors='coerce')
base1['fec_mod'] = base1['fec_mod'].astype(str)
base1['fec_mod'] = np.where(base1['fec_mod'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_mod'].str[-8:], base1['fec_mod'])
base1['fec_mod'] = pd.to_datetime(base1['fec_mod'], errors='coerce')
base1['fec_sol'] = base1['fec_sol'].astype(str)
base1['fec_sol'] = np.where(base1['fec_sol'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_sol'].str[-8:], base1['fec_sol'])
base1['fec_sol'] = pd.to_datetime(base1['fec_sol'], errors='coerce')
base1['fec_anu'] = base1['fec_anu'].astype(str)
base1['fec_anu'] = np.where(base1['fec_anu'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_anu'].str[-8:], base1['fec_anu'])
base1['fec_anu'] = pd.to_datetime(base1['fec_anu'], errors='coerce')

In [133]:
oricas = pd.read_sql_query(f"SELECT id_oricas,ori_cod FROM dim_oricas", con=connection2)
oricas=oricas.rename(columns={"ori_cod":"ori_cas"})
base1=pd.merge(base1,oricas,how='left',on='ori_cas')

base1=base1.drop('ori_cas',axis=1)


cas = pd.read_sql_query(f"SELECT id_cas,cod_cas, cod_red FROM dim_cas where id_red is not null", con=connection2)
cas = cas.dropna()
base1=pd.merge(base1,cas,how='left',on='cod_cas')

base1=base1.drop('cod_cas',axis=1)


red = pd.read_sql_query(f"SELECT id_red,cod_red FROM dim_red", con=connection2)
base1=pd.merge(base1,red,how='left',on='cod_red')

base1=base1.drop('cod_red',axis=1)


oripro = pd.read_sql_query(f"SELECT id_oricas,ori_cod FROM dim_oricas", con=connection2)
oripro=oripro.rename(columns={"ori_cod":"ori_pro"})
oripro=oripro.rename(columns={"id_oricas":"id_oripro"})
base1=pd.merge(base1,oripro,how='left',on='ori_pro')

base1=base1.drop('ori_pro',axis=1)


caspro = pd.read_sql_query(f"SELECT id_cas,cod_cas FROM dim_cas where id_red is not null", con=connection2)
caspro = caspro.dropna()
caspro=caspro.rename(columns={"id_cas":"id_caspro"})
caspro=caspro.rename(columns={"cod_cas":"cas_pro"})
base1=pd.merge(base1,caspro,how='left',on='cas_pro')

base1=base1.drop('cas_pro',axis=1)

are = pd.read_sql_query(f"SELECT id_area,cod_are FROM dim_areas", con=connection2)
base1=pd.merge(base1,are,how='left',on='cod_are')

base1=base1.drop('cod_are',axis=1)


serv= pd.read_sql_query(f"SELECT id_serv,cod_ser FROM dim_servicios", con=connection2)
base1=pd.merge(base1,serv,how='left',on='cod_ser')

base1=base1.drop('cod_ser',axis=1)


activi = pd.read_sql_query(f"SELECT id_activi,cod_act FROM dim_activi", con=connection2)
activi=activi.rename(columns={"id_activi":"id_acti"})
base1=pd.merge(base1,activi,how='left',on='cod_act')

subacti = pd.read_sql_query(f"SELECT id_subacti,cod_sub,cod_act FROM dim_subacti", con=connection2)
subacti["KEY"]=subacti["cod_sub"]+subacti["cod_act"]
subacti=subacti.drop(["cod_sub",'cod_act'], axis=1)
base1["KEY"]=base1["cod_sub"].astype(str)+base1['cod_act'].astype(str)
base1["KEY"]=base1["KEY"].str.replace(' ', '', regex=True)
subacti["KEY"]=subacti["KEY"].str.replace(' ', '', regex=True)
base1 = pd.merge(base1,subacti,how='left',on='KEY')

base1=base1.drop('KEY', axis=1)
base1=base1.drop('cod_act',axis=1)


tipdoc_med = pd.read_sql_query(f"SELECT id_tipdoc,cod_tdo FROM dim_tipdoc", con=connection2)
tipdoc_med = tipdoc_med.rename(columns={"id_tipdoc": "id_tdi_med", "cod_tdo": "cod_tdi_med"})
tipdoc_med['cod_tdi_med']=tipdoc_med['cod_tdi_med'].str.strip()
base1['cod_tdi_med']=base1['cod_tdi_med'].str.strip()
base1 = pd.merge(base1, tipdoc_med, how='left', on='cod_tdi_med')

tipdoc_pac = tipdoc_med.rename(columns={"id_tdi_med": "id_tdi_pac", "cod_tdi_med": "cod_tdi_pac"})
base1['cod_tdi_pac']=base1['cod_tdi_pac'].str.strip()
base1 = pd.merge(base1, tipdoc_pac[['id_tdi_pac', 'cod_tdi_pac']], how='left', on='cod_tdi_pac')
base1['id_tdi_pac'] = base1['id_tdi_pac'].apply(lambda x: int(x) if not pd.isna(x) else x)

estsolcit = pd.read_sql_query(f"SELECT id_estsolcit,cod_esc FROM dim_cexestsolcit", con=connection2)
estsolcit = estsolcit.rename(columns={'id_estsolcit':'id_tci'})
estsolcit = estsolcit.rename(columns={'cod_esc':'cod_tci'})
base1=pd.merge(base1,estsolcit,how='left',on='cod_tci')

base1=base1.drop('cod_tci', axis=1)


tipcita = pd.read_sql_query(f"SELECT id_tipocit,cod_tci FROM dim_tipcita", con=connection2)
tipcita = tipcita.rename(columns={'id_tipocit':'id_cci'})
tipcita = tipcita.rename(columns={'cod_tci':'cod_cci'})
base1=pd.merge(base1,tipcita,how='left',on='cod_cci')

base1=base1.drop('cod_cci', axis=1)


tipemi = pd.read_sql_query(f"SELECT id_tipemi,cod_emi FROM dim_tipemi", con=connection2)
tipemi = tipemi.rename(columns={'id_tipemi':'id_otorga'})
tipemi = tipemi.rename(columns={'cod_emi':'cod_oto'})
base1=pd.merge(base1,tipemi,how='left',on='cod_oto')

base1=base1.drop('cod_oto', axis=1)


base1=base1.rename(columns={'cit_rep':'id_citrep'})


mec = pd.read_sql_query(f"SELECT id_moteli,cod_eli FROM dim_cexmotelicit", con=connection2)
mec = mec.rename(columns={'id_moteli':'id_mec'})
mec = mec.rename(columns={'cod_eli':'cod_mec'})
base1=pd.merge(base1,mec,how='left',on='cod_mec')

base1=base1.drop('cod_mec', axis=1)


eci = pd.read_sql_query(f"SELECT id_estcit,cod_eci FROM dim_estcit", con=connection2)
eci = eci.rename(columns={'id_estcit':'id_eci'})
base1=pd.merge(base1,eci,how='left',on='cod_eci')

base1=base1.drop('cod_eci', axis=1)

enco = pd.read_sql_query(f"SELECT id_esteco,cod_eco FROM dim_cexcitoto", con=connection2)
enco = enco.rename(columns={'id_esteco':'id_enco'})
enco = enco.rename(columns={'cod_eco':'cod_enco'})
base1=pd.merge(base1,enco,how='left',on='cod_enco')

base1=base1.drop('cod_enco', axis=1)

df1_columns = set(base1.columns)
df2_columns = set(base2.columns) 
different_columns = df2_columns - df1_columns
different_columns

#borrando=f"DELETE FROM {dat} WHERE {col_dat} >= TO_DATE('{fecha_ini_str}', 'YYYY-MM-DD') AND {col_dat} < TO_DATE('{fecha_fin_str}', 'YYYY-MM-DD')"
#borrado = connection1.execute(borrando)

comunes = set(base1.columns).intersection(set(base2.columns)) 
base = base1[list(comunes)]
base.to_sql(name=f'{dat}', con=engine1, if_exists='append', index=False,chunksize=5000)


fecha_ini = fecha_fin_mes

finproceso=time.time()
tiempoproceso=finproceso - inicioTiempo
tiempoproceso=round(tiempoproceso,3)
print("Proceso completado satisfactoriamente en " + str(tiempoproceso)+" segundos")

Proceso completado satisfactoriamente en 61391.362 segundos

In [126]:
base1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 44 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cit_num      5 non-null      int64
 1   cod_sub      5 non-null      object
 2   cod_tdi_med  5 non-null      object
 3   num_doc_med  5 non-null      object
 4   fec_cit      5 non-null      datetime64[ns]
 5   hor_ini      5 non-null      object
 6   hor_fin      5 non-null      object
 7   ord_cit      5 non-null      int64
 8   hor_cit      5 non-null      object
 9   id_citrep    5 non-null      object
 10  usu_cre      5 non-null      object
 11  fec_cre      5 non-null      datetime64[ns]
 12  usu_mod      5 non-null      object
 13  fec_mod      5 non-null      datetime64[ns]
 14  fec_sol      5 non-null      object
 15  ip_cre       5 non-null      object
 16  ip_mod       5 non-null      object
 17  mot_cit      0 non-null      object
 18  pac_sec      5 non-null      int64
 19  usu_anu      0 non-null      object
 20  fec_anu      0 non-null      object
 21  ip_anu       0 non-null      object
 22  mod_anu      0 non-null      object
 23  ctr_seg      5 non-null      object
 24  cnv_esp      0 non-null      object
 25  cod_tdi_pac  5 non-null      object
 26  num_doc_pac  5 non-null      object
 27  id_oricas    5 non-null      int64
 28  id_cas       5 non-null      int64
 29  id_red       5 non-null      int64
 30  id_oripro    5 non-null      int64
 31  id_caspro    5 non-null      int64
 32  id_area      5 non-null      int64
 33  id_serv      5 non-null      int64
 34  id_acti      5 non-null      int64
 35  id_subacti   5 non-null      int64
 36  id_tdi_med   5 non-null      int64
 37  id_tdi_pac   5 non-null      int64
 38  id_tci       5 non-null      int64
 39  id_cci       5 non-null      int64
 40  id_otorga    5 non-null      int64
 41  id_mec       5 non-null      int64
 42  id_eci       5 non-null      int64
 43  id_enco      5 non-null      int64
dtypes: datetime64[ns](3), int64(20), object(21)
memory usage: 1.8+ KB

In [3]:
from decouple import config
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text, bindparam, create_engine
import oracledb
import sys
import numpy as np

oracledb.init_oracle_client()
oracledb.version = "11.2.0.4"
sys.modules["cx_Oracle"] = oracledb
un = 'DW_ESSALUD'
pw = 'Dw_Essalud24'
hostname='10.0.1.228'
service_name="devugad"
port = 1521

engine1 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

now2 = datetime.now().strftime('%Y-%m-%d')
print(now2)
query2 = text(f"UPDATE etl_act SET fec_ini = TO_DATE('{now2}','YYYY-MM-DD') WHERE id_mod = 3")

# Ejecutar la consulta
connection1.execute(query2)

2024-02-23

In [4]:
from decouple import config
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text, create_engine
import oracledb
import sys
import numpy as np
import cx_Oracle

DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dw_essalud"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena2  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine2 = create_engine(cadena2)
connection2 = engine2.connect()

oracledb.init_oracle_client()
oracledb.version = "11.2.0.4"
sys.modules["cx_Oracle"] = oracledb
un = 'DW_ESSALUD'
pw = 'Dw_Essalud24'
hostname='10.0.1.228'
service_name="devugad"
port = 1521

engine1 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

connection1 = engine1.connect()

In [9]:
tabla='ctaam10'
col_tabla = "atenambatenfec"
dat= "dat_cext002_essi"
col_dat='ate_fec'


oracledb.init_oracle_client()
oracledb.version = "8.3.0"
sys.modules["cx_Oracle"] = oracledb
un = config("USER4_BDI_POSTGRES")
pw = config("PASS4_BDI_POSTGRES")
hostname=config("HOST4_BDI_POSTGRES")
service_name="WNET"
port = 1527

engine0 = create_engine(f'oracle://{un}:{pw}@',connect_args={
		"host": hostname,
		"port": port,
		"service_name": service_name
	}
)

connection0 = engine0.connect()


query0 = f"""
SELECT
	to_char(d1.ATENAMBATENFEC, 'YYYY-MM-DD HH24:MI:SS') as ATENAMBATENFEC,
	d1.ATENAMBTIPCONCOD,
	d1.ATENAMBCSECOD,
	d1.CPSCOD,
	d1.ATENAMBNUMATECOD,
	d1.TIPCONTLEYCOD,
	d1.RESATENAMBUCOD,
	d1.ORICENASIREFCOD,
	d1.CENASIREFCOD,
	d1.ATENAMBESTREGCOD,
	d1.ATENAMBUSUCRECOD,
	to_char(d1.ATENAMBCREFEC, 'YYYY-MM-DD HH24:MI:SS') as ATENAMBCREFEC,
	d1.ATENAMBUSUMODCOD,
	to_char(d1.ATENAMBMODFEC, 'YYYY-MM-DD HH24:MI:SS') as ATENAMBMODFEC,
	d1.ATENAMBULTREGFEC,
	d1.ATENAMBPACSECNUM,
	per.PERTIPDOCIDENCOD,
	per.PERDOCIDENNUM,
	per.PERNACFEC,
	per.PERSEXOCOD,
	a1.*
FROM ctaam10 d1 
LEFT OUTER JOIN CTDAA10 a1 ON a1.ATENAMBORICENASICOD = d1.ATENAMBORICENASICOD
	AND a1.ATENAMBCENASICOD    = d1.ATENAMBCENASICOD
	AND a1.ATENAMBNUM    = d1.ATENAMBNUM
LEFT OUTER JOIN CMPER10 per ON d1.ATENAMBPACSECNUM = per.PERSECNUM
WHERE d1.{col_tabla} >= TO_DATE('2020-02-05', 'YYYY-MM-DD') AND d1.{col_tabla} < TO_DATE('2020-02-06', 'YYYY-MM-DD')
"""

base1 = pd.read_sql_query(query0, con=connection0)
connection0.close()

print('LECTURA LISTA')

LECTURA LISTA

In [10]:
columnas_eliminar = ['oricenasirefcod','cenasirefcod']

# Eliminar las columnas
base1 = base1.drop(columns=columnas_eliminar)


base1 = base1.rename(columns={
	'atenamboricenasicod': 'ori_cas',
	'atenambcenasicod': 'cod_cas',
	'atenambnum': 'ate_num',
	'atenambatenfec': 'ate_fec',
	'atenambtipconcod': 'tip_con',
	'atenambcsecod': 'cod_cse',
	'cpscod': 'cod_cps',
	'atenambnumatecod': 'ate_cod',
	'tipcontleycod': 'ley_cod',
	'resatenambucod': 'res_cod',
	'atenambestregcod': 'est_reg',
	'atenambusucrecod': 'usu_cre',
	'atenambcrefec': 'fec_cre',
	'atenambusumodcod': 'usu_mod',
	'atenambmodfec': 'fec_mod',
	'atenambultregfec': 'fec_ult_reg',
	'atenambpacsecnum': 'pac_sec',
	'pertipdocidencod': 'cod_tdi_pac',
	'perdocidennum': 'num_doc_pac',
	'conddiagcod': 'cond_diagcod',
	'diagcod': 'diag_cod',
	'atenambdiagord': 'diag_ord',
	'atenambtipodiagcod': 'tip_diag',
	'atenambcasodiagcod': 'caso_diag',
	'diagatenambaltaflag': 'alta_diag',
	'pernacfec': 'fec_nac_pac',
	'persexocod': 'sexo_pac'
})
base1=base1.drop('diagatenambpeas', axis=1)

oricas = pd.read_sql_query(f"SELECT id_oricas, ori_cod FROM dim_oricas", con=connection2)
oricas = oricas.rename(columns={"ori_cod": "ori_cas"})
oricas['ori_cas']=oricas['ori_cas'].str.strip()
base1['ori_cas']=base1['ori_cas'].str.strip()
base1 = pd.merge(base1, oricas, on='ori_cas', how="left")
base1 = base1.drop('ori_cas', axis=1)

cas = pd.read_sql_query(f"SELECT id_cas,cod_cas, cod_red FROM dim_cas where id_cas is not null", con=connection2)
cas = cas.drop_duplicates(subset=['cod_cas'])
cas=cas.dropna()
red = pd.read_sql_query(f"SELECT id_red,cod_red FROM dim_red", con=connection2)
cas_red = pd.merge(cas, red, how="left", on="cod_red")
base1 = pd.merge(base1, cas_red, on='cod_cas', how="left")
base1 = base1.drop('cod_red', axis=1)
base1 = base1.drop('cod_cas', axis=1)

tipcon = pd.read_sql_query(f"SELECT id_tipcon, cod_tipcon FROM dim_tipcon", con=connection2)
tipcon = tipcon.rename(columns={"cod_tipcon": "tip_con"})
tipcon['tip_con']=tipcon['tip_con'].str.strip()
base1['tip_con']=base1['tip_con'].str.strip()
base1 = pd.merge(base1, tipcon, on='tip_con', how="left")
base1 = base1.drop('tip_con', axis=1)

csep = pd.read_sql_query(f"SELECT id_csep, cod_cse FROM dim_csep", con=connection2)
csep['cod_cse']=csep['cod_cse'].str.strip()
base1['cod_cse']=base1['cod_cse'].str.strip()
base1 = pd.merge(base1, csep, on='cod_cse', how="left")
base1 = base1.drop('cod_cse', axis=1)

cps = pd.read_sql_query(f"SELECT id_cps,cod_cps FROM dim_cps", con=connection2)
cps['cod_cps']=cps['cod_cps'].str.strip()
base1['cod_cps']=base1['cod_cps'].str.strip()
base1 = pd.merge(base1, cps, on='cod_cps', how="left")
base1 = base1.drop('cod_cps', axis=1)

numaten = pd.read_sql_query(f"SELECT id_numaten, cod_numaten FROM dim_numaten", con=connection2)
numaten = numaten.rename(columns={"cod_numaten": "ate_cod"})
numaten['ate_cod']=numaten['ate_cod'].str.strip()
base1['ate_cod']=base1['ate_cod'].str.strip()
base1 = pd.merge(base1, numaten, on='ate_cod', how="left")
base1 = base1.drop('ate_cod', axis=1)

ley = pd.read_sql_query(f"SELECT id_tipleycont, cod_tipleycont FROM dim_tipleycont", con=connection2)
ley = ley.rename(columns={"cod_tipleycont": "ley_cod"})
ley['ley_cod']=ley['ley_cod'].str.strip()
base1['ley_cod']=base1['ley_cod'].str.strip()
base1 = pd.merge(base1, ley, on='ley_cod', how="left")
base1 = base1.drop('ley_cod', axis=1)

resaten = pd.read_sql_query(f"SELECT id_resaten, cod_resaten FROM dim_resaten", con=connection2)
resaten = resaten.rename(columns={"cod_resaten": "res_cod"})
resaten['res_cod']=resaten['res_cod'].str.strip()
base1['res_cod']=base1['res_cod'].str.strip()
base1 = pd.merge(base1, resaten, on='res_cod', how="left")
base1 = base1.drop('res_cod', axis=1)

estreg = pd.read_sql_query(f"SELECT id_estreg, cod_est FROM dim_estreg", con=connection2)
estreg = estreg.rename(columns={"cod_est": "est_reg"})
estreg['est_reg']=estreg['est_reg'].str.strip()
base1['est_reg']=base1['est_reg'].str.strip()
base1 = pd.merge(base1, estreg, on='est_reg', how="left")
base1 = base1.drop('est_reg', axis=1)

condiag = pd.read_sql_query(f"SELECT id_condia,cod_con FROM dim_condiag", con=connection2)
base1 = base1.rename(columns={"cond_diagcod": "cod_con"})
condiag['cod_con']=condiag['cod_con'].str.strip()
base1['cod_con']=base1['cod_con'].str.strip()
base1 = pd.merge(base1, condiag, on='cod_con', how="left")
base1 = base1.drop('cod_con', axis=1)

cie10 = pd.read_sql_query(f"SELECT id_cie,cod_cie FROM dim_cie10", con=connection2)
base1 = base1.rename(columns={"diag_cod": "cod_cie"})
cie10['cod_cie']=cie10['cod_cie'].str.strip()
base1['cod_cie']=base1['cod_cie'].str.strip()
base1 = pd.merge(base1, cie10, on='cod_cie', how="left")
base1 = base1.drop('cod_cie', axis=1)

tipdx = pd.read_sql_query(f"SELECT id_tipdx,cod_tdx FROM dim_tipdx", con=connection2)
tipdx = tipdx.rename(columns={"cod_tdx": "tip_diag"})
tipdx['tip_diag']=tipdx['tip_diag'].str.strip()
base1['tip_diag']=base1['tip_diag'].str.strip()
base1 = pd.merge(base1, tipdx, on='tip_diag', how="left")
base1 = base1.drop('tip_diag', axis=1)

casdiag = pd.read_sql_query(f"SELECT id_casdiag,cod_casdiag FROM dim_casdiag", con=connection2)
casdiag = casdiag.rename(columns={"cod_casdiag": "caso_diag"})
casdiag['caso_diag']=casdiag['caso_diag'].str.strip()
base1['caso_diag']=base1['caso_diag'].str.strip()
base1 = pd.merge(base1, casdiag, on='caso_diag', how="left")
base1 = base1.drop('caso_diag', axis=1)

tipdoc = pd.read_sql_query(f"SELECT id_tipdoc,cod_tdo FROM dim_tipdoc", con=connection2)
tipdoc=tipdoc.rename(columns={"id_tipdoc":"id_tdi_pac"})
tipdoc=tipdoc.rename(columns={"cod_tdo":"cod_tdi_pac"})
base1=pd.merge(base1,tipdoc,how='left',on='cod_tdi_pac')

base1['ate_fec'] = base1['ate_fec'].astype(str)
base1['ate_fec'] = np.where(base1['ate_fec'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['ate_fec'].str[-8:], base1['ate_fec'])
base1['ate_fec'] = pd.to_datetime(base1['ate_fec'], errors='coerce')
base1['fec_cre'] = base1['fec_cre'].astype(str)
base1['fec_cre'] = np.where(base1['fec_cre'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_cre'].str[-8:], base1['fec_cre'])
base1['fec_cre'] = pd.to_datetime(base1['fec_cre'], errors='coerce')
base1['fec_mod'] = base1['fec_mod'].astype(str)
base1['fec_mod'] = np.where(base1['fec_mod'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_mod'].str[-8:], base1['fec_mod'])
base1['fec_mod'] = pd.to_datetime(base1['fec_mod'], errors='coerce')
base1['fec_ult_reg'] = base1['fec_ult_reg'].astype(str)
base1['fec_ult_reg'] = np.where(base1['fec_ult_reg'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_ult_reg'].str[-8:], base1['fec_ult_reg'])
base1['fec_ult_reg'] = pd.to_datetime(base1['fec_ult_reg'], errors='coerce')
base1['fec_nac_pac'] = base1['fec_nac_pac'].astype(str)
base1['fec_nac_pac'] = np.where(base1['fec_nac_pac'].str.startswith('0001-01-01'), '1999-01-01 ' + base1['fec_nac_pac'].str[-8:], base1['fec_nac_pac'])
base1['fec_nac_pac'] = pd.to_datetime(base1['fec_nac_pac'], errors='coerce')

print('EMPAREJAMIENTOS LISTOS')

EMPAREJAMIENTOS LISTOS

In [12]:
print(base1.shape)

(132295, 29)

In [11]:
base2 = pd.read_sql_query(f"SELECT * FROM {dat} WHERE ROWNUM <= 10", con=connection1)


df1_columns = set(base1.columns)
df2_columns = set(base2.columns) 
different_columns = df2_columns - df1_columns
different_columns

#borrando=f"DELETE FROM {dat} WHERE {col_dat} >= TO_DATE('{fecha_ini_str}', 'YYYY-MM-DD') AND {col_dat} < TO_DATE('{fecha_fin_str}', 'YYYY-MM-DD')"
#borrado = connection1.execute(borrando)
print('BORRADO LISTO, SUBIENDO...')

BORRADO LISTO, SUBIENDO...

In [12]:

comunes = set(base1.columns).intersection(set(base2.columns))
base = base1[list(comunes)]

In [13]:
base.shape

(132295, 28)

In [24]:
base.loc[:, base.select_dtypes(['object']).columns] = base.select_dtypes(['object']).astype(str)

/tmp/ipykernel_2272710/3676875802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  base.loc[:, base.select_dtypes(['object']).columns] = base.select_dtypes(['object']).astype(str)

In [15]:
base.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132295 entries, 0 to 132294
Data columns (total 28 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id_tipleycont  132295 non-null  int64
 1   fec_ult_reg    2778 non-null    datetime64[ns]
 2   ate_num        132285 non-null  float64
 3   id_condia      132285 non-null  float64
 4   id_tdi_pac     132245 non-null  float64
 5   id_oricas      132285 non-null  float64
 6   fec_nac_pac    132245 non-null  datetime64[ns]
 7   id_cie         132285 non-null  float64
 8   id_csep        0 non-null       float64
 9   id_red         132285 non-null  float64
 10  id_casdiag     132285 non-null  float64
 11  id_estreg      132295 non-null  int64
 12  usu_mod        60280 non-null   object
 13  sexo_pac       132245 non-null  object
 14  id_cps         132295 non-null  int64
 15  id_cas         132285 non-null  float64
 16  num_doc_pac    132245 non-null  object
 17  fec_cre        132295 non-null  datetime64[ns]
 18  id_tipdx       132285 non-null  float64
 19  id_tipcon      132295 non-null  int64
 20  id_resaten     132295 non-null  int64
 21  usu_cre        132295 non-null  object
 22  pac_sec        132295 non-null  int64
 23  diag_ord       132285 non-null  float64
 24  id_numaten     0 non-null       float64
 25  ate_fec        132295 non-null  datetime64[ns]
 26  fec_mod        132295 non-null  datetime64[ns]
 27  alta_diag      132285 non-null  object
dtypes: datetime64[ns](5), float64(12), int64(6), object(5)
memory usage: 29.3+ MB

In [16]:
base.to_sql(name=f'{dat}', con=engine1, if_exists='append', index=False,chunksize=250000)

finproceso=time.time()
tiempoproceso=finproceso - inicioTiempo
tiempoproceso=round(tiempoproceso,3)
print("Proceso completado satisfactoriamente en " + str(tiempoproceso)+" segundos")
    
connection1.close()
connection2.close()


engine1.dispose()
engine2.dispose()

NameError: name 'inicioTiempo' is not defined