In [3]:
from decouple import config
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text
import oracledb
import sys

In [6]:
DB_USER=config("USER2_BDI_POSTGRES")
DB_PASSWORD=config("PASS2_BDI_POSTGRES")
DB_NAME="dw_sap"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_POSTGRES")
cadena2  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine2 = create_engine(cadena2)
connection2 = engine2.connect()

In [31]:
ID = pd.read_sql_query('SELECT * FROM "ID"', con=connection2)

In [34]:
ids_to_filter = [
    '6159828', '7820416', '9386448', '6097016', '9739290', '9590494', '8213953', '3380021',
    '4005616', '3940150', '65989', '3152294', '3603256', '323565', '7091412', '9356378',
    '3946249', '8038254', '29597417', '7875423', '6983196', '3742421', '6719448', '3196245',
    '3932327', '229599', '6120449', '4379839', '10648301', '10059646', '4150758', '3409123',
    '8437388', '414889143', '10038299', '1269949', '5515555', '3294433', '10790072',
    '18092775', '40453581', '2106970', '45867215', '10075442', '2917757', '4017428',
    '125871', '10515168', '42949897', '41399338', '2619467', '9920282', '41826518',
    '43477995', '44068191', '40881400', '40816987', '5102654', '21462316', '8140525',
    '7455060', '4855038', '41199012', '9304240', '43009786', '5107039', '3713359',
    '9314041', '3297914', '4943568', '1270811', '40670050', '10417197', '40637150',
    '5323999', '9232143', '20044227', '8838134', '41258664', '7420147', '5187973',
    '4208268', '20068426', '17844995', '22967964', '2763915', '800207', '8095940',
    '4648451', '3946218', '2625074', '46103759', '43226300', '70242309', '72472114',
    '7749421', '4402966', '42061924', '42239696', '46160339', '3930529', '41959714',
    '45834620', '40973900', '70364472', '41065250', '8919417', '4127458', '46612212',
    '41200046', '7574695', '80240178', '21575212', '7202374', '46293657', '42047386',
    '10685352', '7225909', '25615054', '5669956', '6665150', '29688737', '43888717',
    '22300684', '45206525', '29352255', '10300815', '9748606', '25487027', '9849470',
    '41381090', '6885431', '41718126', '32916440', '5348132', '47238179', '7533334',
    '9464342', '76820496', '44747017', '7258555', '5062130', '10325905', '41322202',
    '7031780', '41274582', '43433686', '10474922', '8037215', '45744355', '8320766',
    '7469289', '43410916', '41955289', '40501864', '10308498', '42653003', '73217478',
    '74900561', '30832437', '40444861', '43737726', '74303902', '10228171', '21560581',
    '10506902', '9799730', '22673510', '40933597', '42631479', '45294762', '10552684',
    '44589796', '44288282', '29472416', '7830864', '44387786', '40129817', '44120851'
]

ids_to_filter
ID2 = ID[ID['Número ID'].isin(ids_to_filter)]

In [35]:
ID2

,ID,Motivo medida,Status de actividad,Sociedad,División de personal,Grupo de personal,Área de personal,Subdivisón personal,Área de nómina,Relación laboral,...,FECHA TIPO,Inicio de validez_y,Clase ID,Número ID,Clase beneficiario,Clave de receptor,Número de asociado,Fecha de inscripción,Tipo Pensión,Tipo Comisión
14356,11811389,P199,3,0200,0206,7,PR,0014,P1,03,...,12/31/1980,12/31/1980,01,10552684,0001,PRIMA,506380BOAVN0,5/31/1996,1,None
28589,12848991,P214,3,0100,0100,6,ME,0001,P1,03,...,8/1/1985,8/1/1985,01,29688737,0001,PRIMA,507491GDHIR3,8/23/1996,1,1
30652,13108496,P199,3,0200,0206,3,PR,0056,P2,03,...,3/4/1995,3/4/1995,01,25615054,0001,INTEGRA,523891OEVIS7,1/1/1996,None,1
30653,13108496,P199,3,0200,0206,3,PR,0056,P2,03,...,3/4/1995,3/4/1995,01,25615054,0001,INTEGRA,523891OEVIS7,1/1/1996,None,1
32061,13222377,P208,3,0200,0206,2,PR,0012,P2,03,...,9/9/1997,9/9/1997,01,32916440,0001,PROFUTUR,553121JHBRA2,6/12/1996,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177613,16644244,P400,0,0100,0100,9,EJ,0001,P2,04,...,1/18/2022,1/18/2022,01,29352255,0001,PRIMA,569843JDAGN7,None,None,None
179265,16646968,P400,0,0200,0206,9,EJ,0022,P2,04,...,6/30/2022,7/1/2022,01,44589796,0001,SNP,None,None,None,None
180425,16648063,P102,3,0200,0206,2,TE,0014,P2,03,...,10/28/2022,10/28/2022,01,72472114,0001,SNP,None,None,None,None
180426,16648063,P102,3,0200,0206,2,TE,0014,P2,03,...,10/28/2022,10/28/2022,01,72472114,0001,SNP,None,None,None,None
180538,16648135,P400,0,0200,0206,9,EJ,0056,P2,04,...,12/31/2022,1/1/2023,01,44120851,0001,SNP,None,None,None,None

In [36]:
df = pd.read_excel('usuarios_ad.xlsx', engine='openpyxl')

# Eliminar filas vacías
df.dropna(how='all', inplace=True)

# Eliminar la palabra "DNI" en la segunda columna
df.iloc[:, 1] = df.iloc[:, 1].str.replace('DNI ', '')

# Guardar el DataFrame transformado a un nuevo archivo Excel
df.to_excel('cleaned_file.xlsx', index=False, engine='openpyxl')

In [38]:
ID3 = pd.merge(ID2, df, how='left', left_on='Número ID', right_on='OfficePhone')

In [39]:
ID3

,ID,Motivo medida,Status de actividad,Sociedad,División de personal,Grupo de personal,Área de personal,Subdivisón personal,Área de nómina,Relación laboral,...,Clase ID,Número ID,Clase beneficiario,Clave de receptor,Número de asociado,Fecha de inscripción,Tipo Pensión,Tipo Comisión,mail,OfficePhone
0,11811389,P199,3,0200,0206,7,PR,0014,P1,03,...,01,10552684,0001,PRIMA,506380BOAVN0,5/31/1996,1,None,NaN,NaN
1,12848991,P214,3,0100,0100,6,ME,0001,P1,03,...,01,29688737,0001,PRIMA,507491GDHIR3,8/23/1996,1,1,NaN,NaN
2,13108496,P199,3,0200,0206,3,PR,0056,P2,03,...,01,25615054,0001,INTEGRA,523891OEVIS7,1/1/1996,None,1,NaN,NaN
3,13108496,P199,3,0200,0206,3,PR,0056,P2,03,...,01,25615054,0001,INTEGRA,523891OEVIS7,1/1/1996,None,1,NaN,NaN
4,13222377,P208,3,0200,0206,2,PR,0012,P2,03,...,01,32916440,0001,PROFUTUR,553121JHBRA2,6/12/1996,None,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,16644244,P400,0,0100,0100,9,EJ,0001,P2,04,...,01,29352255,0001,PRIMA,569843JDAGN7,None,None,None,NaN,NaN
109,16646968,P400,0,0200,0206,9,EJ,0022,P2,04,...,01,44589796,0001,SNP,None,None,None,None,NaN,NaN
110,16648063,P102,3,0200,0206,2,TE,0014,P2,03,...,01,72472114,0001,SNP,None,None,None,None,NaN,NaN
111,16648063,P102,3,0200,0206,2,TE,0014,P2,03,...,01,72472114,0001,SNP,None,None,None,None,NaN,NaN
112,16648135,P400,0,0200,0206,9,EJ,0056,P2,04,...,01,44120851,0001,SNP,None,None,None,None,NaN,NaN

In [41]:
selected_columns_df = ID3[['Número ID', 'Género', 'Fecha de nacimiento', 'OfficePhone', 'mail', 'Área de personal']]

# Guardar el nuevo DataFrame a un archivo Excel
selected_columns_df.to_excel('selected_columns_file.xlsx', index=False, engine='openpyxl')