In [1]:
from decouple import config
from sqlalchemy import create_engine
import pandas as pd
from datetime import datetime, timedelta, date
import time 
from sqlalchemy import text
import oracledb
import sys

In [2]:
#CONEXIONES DESTINO
DB_USER=config("USER2_BDI_DW")
DB_PASSWORD=config("PASS2_BDI_DW")
DB_NAME="INDICADORES_ESSALUD"
DB_PORT="5432"
DB_HOST=config("HOST2_BDI_DW")
cadena2  = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine2 = create_engine(cadena2)
connection2 = engine2.connect()

In [3]:
# MAESTROS GRANDES
paciente = pd.read_sql_query(f"SELECT id_paciente,per_sec FROM dim_paciente limit 500000", con=connection2)
#personal = pd.read_sql_query(f"SELECT id_personal,num_doc FROM dim_personal", con=connection2)
paciente_ini = paciente
#paciente['per_sec']=paciente['per_sec'].astype(str).str.strip()
#paciente["per_sec"]=paciente["per_sec"].str.replace(' ', '', regex=True)
#paciente["per_sec"]=paciente["per_sec"].str.replace('.0', '', regex=True)

In [15]:
paciente = pd.read_sql_query(f"SELECT id_paciente,per_sec FROM dim_paciente WHERE id_paciente=6851596", con=connection2)

In [17]:
paciente['per_sec'] = None

In [25]:
paciente

   id_paciente  per_sec
0      6851596     <NA>

In [30]:
paciente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_paciente  1 non-null      int64
 1   per_sec      0 non-null      Int64
dtypes: Int64(1), int64(1)
memory usage: 145.0 bytes

In [21]:
paciente['per_sec'] = pd.to_numeric(paciente['per_sec'], errors='coerce').astype('Int64')

In [ ]:
base1['per_sec'] = pd.to_numeric(base1['per_sec'], errors='coerce').astype('Int64')

In [7]:
base1['per_sec'] = pd.to_numeric(base1['per_sec'], errors='coerce').astype('Int64')

In [31]:
paciente['per_sec']=paciente['per_sec'].astype(int)
#paciente["per_sec"]=paciente["per_sec"].str.replace(' ', '', regex=True)
#paciente["per_sec"]=paciente["per_sec"].str.replace('.0', '', regex=True)

In [7]:
paciente_ini

        id_paciente per_sec
0           6851594  114177
1           6851595  114179
2           6851596    1141
3           6851598  114182
4           6851599  114183
...             ...     ...
499995      7375227    1952
499996      7375228    1954
499997      7375229    1955
499998      7375230    1956
499999      7375231    1957

[500000 rows x 2 columns]

In [5]:
connection2.close()

engine2.dispose()